In [1]:
import pandas as pd 
import numpy as np

## 1. Write a Python function that takes your name and print a greeting message to you.


In [4]:
def Greeting(name):
    print('Hello,' + name)

my_input = input('Enter your name: ')
Greeting(my_input)

Enter your name: ahmed
Hello,ahmed


## 2. Write a Python function that takes a list of numbers and find sum of all numbers in this list. Then return result in variable named total_sum.


In [6]:
def summ(nums):
    return sum(nums)
my_input= [4,4,3,2,5,7]
summ(my_input)

25

## 3. Write a Python function that takes a list of words and print a full sentence of these words.

In [6]:
def func(words_list):
    temp_str = ''
    for i in words_list:
        temp_str += i
        temp_str+=' '
    return temp_str

my_input =input('Enter elements of a list separated by space ').split()
print(func(my_input))

Enter elements of a list separated by space my lol iz lol
my lol iz lol 


## 4. Write a Python function that takes a list and returns a new list with unique elements of the first list.


In [7]:
my_input= [4,4,3,2,5,7] 
def uni_list(li):
    return list(set(li))

uni_list(my_input)

[2, 3, 4, 5, 7]

## 5. Write a Python function that takes three numbers defined as global variables and find the maximum number.


In [9]:
a= 6
b = 2
c = 9
def return_max(a,b,c):
    if a > b and a > c :
        return a
    elif b > a and b > c :
        return b 
    else:
        return c
    
return_max(a,b,c)

9

## 6. Write a Python function that takes a number as default argument, and check the number is prime or not.


In [12]:
my_input = int(input('Enter num to check :'))
def is_prime(num):
    num = 3
    prime = True
    for i in range(2,10):
        if num % i == 0 and i != num:
            prime = False 
            break
        else:
            prime = True
    return prime
is_prime(my_input)

Enter num to check :11


True

## 7. Write a Python function to reverse a list of items.


In [13]:
my_input=input('Enter list').split()
def rev_list(li):
    return li[::-1]

print(rev_list(my_input))

Enter list1 2 3 4
['4', '3', '2', '1']


## 8. Create an array of shape (3,5).


In [14]:
arr = np.array([[1, 1, 1, 1, 1], [2, 2, 2 , 2, 2], [3, 3, 3, 3, 3]])
print(arr)

[[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]]


## 9. Create an array of 4 rows and 3 columns, with positive random fractions.


In [15]:
arr = np.random.rand(4, 3)
print(arr)

[[0.46009034 0.43975122 0.12409052]
 [0.00592949 0.0796373  0.88406802]
 [0.51772253 0.40797379 0.16390173]
 [0.13995066 0.7422259  0.40236975]]


## 10. Create a random 2D array of Gaussian distributed fractions.


In [16]:
x = np.random.randn(2, 2)
print(x)

[[-1.70505652 -0.1142239 ]
 [ 0.33368709 -0.18940482]]


## 11. Create a dataframe of different students’ data (name, age, class).


In [17]:
info = [('Sia', 18, 'Math'), ('Dawson',18 , 'Male'), ('Gaafar', 20, 'Memes'), ('Maria', 22, 'English'), ('Lol', 24, 'Arabic')]
df = pd.DataFrame(info, columns=['name', 'age', 'class'])
print(df)

     name  age    class
0     Sia   18     Math
1  Dawson   18     Male
2  Gaafar   20    Memes
3   Maria   22  English
4     Lol   24   Arabic


## 12. Create a dataframe from below given lists, then save it in an excel file.


In [18]:
Country= ["Brazil", "Russia", "India", "China", "South Africa"]
capital= ["Brasilia", "Moscow", "New Dehli", "Beijing", "Pretoria"]
area= [8.516, 17.10, 3.286, 9.597, 1.221]
population = [200.4, 143.5, 1252, 1357, 52.98]

data_dict = zip(Country,capital,area,population)

df= pd.DataFrame(data_dict , columns=['Country', 'capital','area','population'])
df

Country    capital    area  population
0        Brazil   Brasilia   8.516      200.40
1        Russia     Moscow  17.100      143.50
2         India  New Dehli   3.286     1252.00
3         China    Beijing   9.597     1357.00
4  South Africa   Pretoria   1.221       52.98